services:
  postgres:
    container_name: django_postgres_DB
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./DB:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - postgres

  sample-django:
    image: kinkinov/training:sample-django
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@django_postgres_DB/${DB_NAME}
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    networks:
      - postgres
    restart: unless-stopped
    ports:
      - "80:8000"

volumes:
  DB:

networks:
  postgres:
    driver: bridge
